# Chapter 4: NumPy Basics: Arrays and Vectorized Computation

- Practical tools like `pandas` rely on `NumPy`.
- `NumPy` is very fast at handling arrays (vectors).

In [17]:
# Load numpy
import numpy as np

## The NumPy `ndarray`: A Multidimensional Array Object

The N-dimensional array facilitates creation of higher dimensional data containers (e.g. matrices) that can be operated on for entire objects at once.

In [18]:
# Create 2D array
data = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])

In [19]:
# Operate on array
data * 5.5

array([[  8.25,  -0.55,  16.5 ],
       [  0.  , -16.5 ,  35.75]])

All arrays have dimensionality (shape) and one data type across the array.

In [20]:
print(data.shape)
print(data.dtype)

(2, 3)
float64


### Creating ndarrays

When arrays are created using nested lists, dimensionality is inferred outside in (dim 1 = outermost list dimension, dim 2 = next inner list dimension, dim 3 = next inner list dimension, etc.)

In [21]:
# Create a 3D array
arr = np.array(
    [
        [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]],
        [[13, 14, 15], [16, 17, 18], [19, 20, 21], [22, 23, 24]],
    ]
)

print(arr.shape)
arr

(2, 4, 3)


array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

Produce an array containing `0` or `1` using the respective functions, passing dimensions as a tuple.

In [22]:
# Provide dimensionality
np.zeros((10, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [23]:
# Provide another array to copycat dimensionality from
np.ones_like(arr)

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

### Data types

We can specify data types for ndarrays (float, int, signed/unsigned, string, etc.) at point of creation. For now, let Python handle it...

In [41]:
# Force as complex number
arr1 = np.array(
    [
        [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]],
        [[13, 14, 15], [16, 17, 18], [19, 20, 21], [22, 23, 24]],
    ],
    dtype=np.float64
)

# Automatic
arr2 = np.array(
    [
        [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]],
        [[13, 14, 15], [16, 17, 18], [19, 20, 21], [22, 23, 24]],
    ]
)

# Show type
print(arr1.dtype)
print(arr2.dtype)

float64
int64


We can coerce array data type using the `astype` method. Note that `astype` doesn't mutate the original array, functional style.

In [44]:
# Convert arr2 to same dtype as arr1
arr2 = arr2.astype(np.float64)

print(arr2.dtype)

float64


### Arithmetic

### Basic Indexing and Slicing

### Boolean Indexing

### Fancy Indexing

### Transposing Arrays and Swapping Axes

## Pseudo RNG

## Universal Functions: Fast Element-Wise Array Functions