# Chapter 4: NumPy Basics: Arrays and Vectorized Computation

- Practical tools like `pandas` rely on `NumPy`.
- `NumPy` is very fast at handling arrays (vectors).

In [151]:
# Load numpy
import numpy as np

## The NumPy `ndarray`: A Multidimensional Array Object

The N-dimensional array facilitates creation of higher dimensional data containers (e.g. matrices) that can be operated on for entire objects at once.

In [152]:
# Create 2D array
data = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])

In [153]:
# Operate on array
data * 5.5

array([[  8.25,  -0.55,  16.5 ],
       [  0.  , -16.5 ,  35.75]])

All arrays have dimensionality (shape) and one data type across the array.

In [154]:
print(data.shape)
print(data.dtype)

(2, 3)
float64


### Creating ndarrays

When arrays are created using nested lists, dimensionality is inferred outside in (dim 1 = outermost list dimension, dim 2 = next inner list dimension, dim 3 = next inner list dimension, etc.)

In [155]:
# Create a 3D array
arr = np.array(
    [
        [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]],
        [[13, 14, 15], [16, 17, 18], [19, 20, 21], [22, 23, 24]],
    ]
)

print(arr.shape)
arr

(2, 4, 3)


array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

Produce an array containing `0` or `1` using the respective functions, passing dimensions as a tuple.

In [156]:
# Provide dimensionality
np.zeros((10, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [157]:
# Provide another array to copycat dimensionality from
np.ones_like(arr)

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

### Data types

We can specify data types for ndarrays (float, int, signed/unsigned, string, etc.) at point of creation. For now, let Python handle it...

In [158]:
# Force as complex number
arr1 = np.array(
    [
        [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]],
        [[13, 14, 15], [16, 17, 18], [19, 20, 21], [22, 23, 24]],
    ],
    dtype=np.float64,
)

# Automatic
arr2 = np.array(
    [
        [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]],
        [[13, 14, 15], [16, 17, 18], [19, 20, 21], [22, 23, 24]],
    ]
)

# Show type
print(arr1.dtype)
print(arr2.dtype)

float64
int64


We can coerce array data type using the `astype` method. Note that `astype` doesn't mutate the original array, functional style.

In [159]:
# Convert arr2 to same dtype as arr1
arr2 = arr2.astype(np.float64)

print(arr2.dtype)

float64


### Arithmetic

Arithmetic operations between equal-size arrays apply it element-wise

In [160]:
arr2 * arr2

array([[[  1.,   4.,   9.],
        [ 16.,  25.,  36.],
        [ 49.,  64.,  81.],
        [100., 121., 144.]],

       [[169., 196., 225.],
        [256., 289., 324.],
        [361., 400., 441.],
        [484., 529., 576.]]])

Arithmetic operations between equal-size array and a scalar recycles the scalar to each element.

In [161]:
arr2 * (1 / 3)

array([[[0.33333333, 0.66666667, 1.        ],
        [1.33333333, 1.66666667, 2.        ],
        [2.33333333, 2.66666667, 3.        ],
        [3.33333333, 3.66666667, 4.        ]],

       [[4.33333333, 4.66666667, 5.        ],
        [5.33333333, 5.66666667, 6.        ],
        [6.33333333, 6.66666667, 7.        ],
        [7.33333333, 7.66666667, 8.        ]]])

Comparisons between equal-size arrays return a boolean array.

In [162]:
arr3 = np.array([[1, 2, 3], [4, 5, 6]])
arr4 = np.array([[6, 5, 4], [3, 2, 1]])

arr3 > arr4

array([[False, False, False],
       [ True,  True,  True]])

### Basic Indexing and Slicing

#### List vs. Array

Arrays can be sliced / subsetted like lists. Unlike lists, the created slices are views connected to the original array. Modifying the slices modify the original array.

In [163]:
# Create a list, mutate slice.
## Create a list
ex_list = list(range(12))

## Create and mutate slice
ex_list_slice = ex_list[5:8]
ex_list_slice[0:2] = 12, 12

## Show list is unchanged
ex_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [164]:
# Create an array, mutate slice.
## Create array
ex_arr = np.arange(12)

## Create and mutate slice
ex_arr_slice = ex_arr[5:8]
ex_arr_slice[0:2] = 12, 12

## Show array is changed
ex_arr

array([ 0,  1,  2,  3,  4, 12, 12,  7,  8,  9, 10, 11])

#### Multidimensional subsets

Multidimensional arrays are sliced outside-in.

In [165]:
# Example from earlier: arr2
arr2 = np.array(
    [
        [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]],
        [[13, 14, 15], [16, 17, 18], [19, 20, 21], [22, 23, 24]],
    ]
)

print(arr2)
print(arr2.shape)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]]
(2, 4, 3)


In [166]:
# To get the value 12
arr2[0][3][2]

# Or
arr2[0, 3, 2]

np.int64(12)

In [167]:
# To get the last 22, 23, 24 array
arr2[1, 3]

array([22, 23, 24])

In [168]:
# Slice only using ranges to keep dimensionality in the array
arr2[0:1, 1:3, 0:2]

array([[[4, 5],
        [7, 8]]])

In [169]:
# Mix index and slices to reduce dimensionality in the array
arr2[0, 1:3, 0:2]

array([[4, 5],
       [7, 8]])

### Boolean Indexing

This allows for subsetting of an array using a boolean array. Boolean indexing can be mixed with normal indexing and slicing.

In [170]:
# Create example data
names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])
data = np.array([[4, 7], [0, 2], [-5, 6], [0, 0], [1, 2], [-12, -4], [3, 4]])

In [171]:
# Subset data for everyone with names equal to Joe
data[names == "Joe"]

array([[  0,   2],
       [-12,  -4],
       [  3,   4]])

In [172]:
# Subset data for everyone with names equal to Joe, then grab 2nd index of array
data[names == "Joe", 1]

array([ 2, -4,  4])

In [173]:
# Subset data for everyone with names equal to Joe, then grab 2nd index of array, keeping dimensionality
data[names == "Joe", 1:]

array([[ 2],
       [-4],
       [ 4]])

Boolean indexing and assigning the slice to a variable creates a copy of the data. This is unlike simple indexing.

In [174]:
# Create slice
data_sub = data[names == "Joe", 1:]

In [175]:
# Whole array
data

array([[  4,   7],
       [  0,   2],
       [ -5,   6],
       [  0,   0],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [176]:
# Mutate slice
data_sub[:] = 3

In [177]:
# Show whole array isn't modified
data

array([[  4,   7],
       [  0,   2],
       [ -5,   6],
       [  0,   0],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

To mutate the array, set values directly.

In [178]:
data[names == "Joe", 1:] = 3
data

array([[  4,   7],
       [  0,   3],
       [ -5,   6],
       [  0,   0],
       [  1,   2],
       [-12,   3],
       [  3,   3]])

### Fancy Indexing

This is indexing using integer arrays. For example, with a 2D array:

In [179]:
# Create array
arr = np.arange(32).reshape((8, 4))

# Show array
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

Subset the array by passing an array identifying the desired indices. If only one array is passed, the original array is subsetted along dim 1 (rows).

In [180]:
# Subset desired rows (forward direction)
arr[np.array([4, 3, 0, 6])]

array([[16, 17, 18, 19],
       [12, 13, 14, 15],
       [ 0,  1,  2,  3],
       [24, 25, 26, 27]])

In [181]:
# Subset desired rows (reversed direction)
arr[np.array([-1, -2, -8])]

array([[28, 29, 30, 31],
       [24, 25, 26, 27],
       [ 0,  1,  2,  3]])

If two arrays are passed, the original array is subsetted along both dimensions, with elements returned based on their row and column indices.

In [182]:
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


In [183]:
# Subset desired elements (based on row and col indices)
# Selected elements are: (1, 0), (5, 3), (7, 1), (2, 2)
arr[np.array([1, 5, 7, 2]), np.array([0, 3, 1, 2])]

array([ 4, 23, 29, 10])

To subset an array via fancy indexing on all dimensions, perform them sequentially. 

In [184]:
# First subset: subset rows (dim1)
arr_sub1 = arr[np.array([1, 5, 7, 2])]
print("First subset results", "\n", arr_sub1, "\n")

# Second subset: subset cols (dim2)
arr_sub2 = arr_sub1[:, np.array([0, 3])]
print("Second subset results", "\n", arr_sub2, "\n")

# Perform both at once
arr_sub = arr[np.array([1, 5, 7, 2])][:, np.array([0, 3])]
print("One-step subset results", "\n", arr_sub, "\n")

First subset results 
 [[ 4  5  6  7]
 [20 21 22 23]
 [28 29 30 31]
 [ 8  9 10 11]] 

Second subset results 
 [[ 4  7]
 [20 23]
 [28 31]
 [ 8 11]] 

One-step subset results 
 [[ 4  7]
 [20 23]
 [28 31]
 [ 8 11]] 



Setting behaviours for fancy indexing is similar to boolean indexing:
- Assign new variable = not mutable
- Mutate by setting to original data

In [185]:
# Original array
arr = np.arange(32).reshape((8, 4))
print("Original array", "\n", arr, "\n")

# Mutated array
arr[np.array([1, 5, 7, 2]), np.array([0, 3, 1, 2])] = 0
print("Mutated array", "\n", arr, "\n")

Original array 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]] 

Mutated array 
 [[ 0  1  2  3]
 [ 0  5  6  7]
 [ 8  9  0 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22  0]
 [24 25 26 27]
 [28  0 30 31]] 



### Transposing Arrays and Swapping Axes

The `T` attribute of arrays provide a view of the arrays with dimensions flipped. No data is mutated.

In [186]:
arr = np.arange(15).reshape((3, 5))
print("Original array", "\n", arr, "\n")
print("Transposed array", "\n", arr.T, "\n")

Original array 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] 

Transposed array 
 [[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]] 



## Pseudo RNG

NumPy can be used to create arrays containing random values quickly from various distributions.

In [187]:
samples = np.random.standard_normal(size=(2, 3, 4))
samples

array([[[ 2.25473894, -1.55435884, -0.7624146 , -0.99894309],
        [-0.9041087 ,  1.14696748, -1.62168997, -0.45695368],
        [-0.36590572,  0.39432569,  1.66935472, -1.27559373]],

       [[-0.92443397,  1.37792812, -0.53353443, -0.09242011],
        [ 1.50256017, -0.73321137,  0.35064304, -1.89130464],
        [ 0.16614305, -1.99774939,  0.60917237, -1.89780377]]])

In [192]:
samples = np.random.binomial(30, 0.4, size=(2, 3, 4))
samples

array([[[13, 13, 10, 15],
        [11, 14, 20, 11],
        [15, 14, 10, 17]],

       [[13, 10, 11, 16],
        [14, 15, 12, 11],
        [17,  9, 11, 12]]], dtype=int32)

## Universal Functions: Fast Element-Wise Array Functions

## Array-Oriented Programming with Arrays

### Expressing Conditional Logic as Array Operations

### Mathematical and Statistical Methods

### Methods for Boolean Arrays

### Sorting

### Unique and Other Set Logic

## File I/O with Arrays

## Linear Algebra

## Example: Random Walks

### Simulating Many Random Walks at Once